# Generated by Django 5.2.1 on 2025-06-11 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dano', models.CharField(choices=[('fisico', 'Físico'), ('tecnologico', 'Tecnológico')], max_length=20)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(default='Media', max_length=20)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='main.usuarios')),
            ],
        ),
    ]
