# Generated by Django 5.2.1 on 2025-06-11 20:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='fecha_reporte',
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuarios'),
        ),
    ]
