# Generated by Django 5.2.1 on 2025-06-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_reporte_fecha_reporte_reporte_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='reportes/'),
        ),
    ]
