# Generated by Django 5.2.1 on 2025-06-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_reporte_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='id',
        ),
        migrations.AddField(
            model_name='reporte',
            name='id_reporte',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
