# Generated by Django 5.2.1 on 2025-06-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_reporte_id_reporte_id_reporte'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuarios',
            new_name='Usuario',
        ),
    ]
